name: eventuous_simplified_example
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0 <3.0.0'


dependencies:
  meta: ^1.7.0
  freezed_annotation: ^1.1.0
  eventuous_simplified:
    path: ../
  json_annotation: ^4.4.0
  uuid: ^3.0.5

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  freezed: ^1.1.1
  build_runner: ^2.1.7
  json_serializable: ^6.1.4